# Generated by Django 5.0.2 on 2024-02-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_alter_user_featured_img_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
