# Generated by Django 5.0.2 on 2024-02-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_alter_post_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
