# Generated by Django 5.0.2 on 2024-02-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_post_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
